export const aboutMe = {
  name: "Asem Qaffaf",
  brief:
    "As a Senior Software Engineer with extensive experience in Japan, Europe, and the USA, I excel in delivering innovative solutions using my strong JavaScript skills. Known for exceptional organization and self-motivation, I am deeply committed to making a positive impact in the tech industry, consistently striving for excellence and significantly contributing to the field of software engineering.",
  profilePic: "/images/asem.png",
  // flagUrl: "/images/jordan-flag.png",
  flagUrl: "/images/japan-flag.png",
  lastWord: "",
} as const;

export const typeWriteList = [
  "Deliver Digital Transformations.",
  "Enabling our clients to accelerate.",
  "Innovating the future, one pixel at a time.",
  "Coding the path to digital excellence.",
  "Transforming challenges into digital solutions.",
  "Empowering success through technology.",
  "Where code meets creativity.",
  "Driving progress with every line of code.",
  "Shaping the digital world, together.",
  "Engineering dreams into digital realities.",
  "Technology as a catalyst for growth.",
  "Innovation at the speed of code.",
  "Digital excellence, our core mission.",
  "Coding today for a better tomorrow.",
  "Breaking barriers with digital innovation.",
  "Crafting the future with technology.",
  "Where technology meets purpose.",
  "Revolutionizing industries through digital expertise.",
  "Empowering visions with virtual solutions.",
  "Coding a smarter world.",
  "Accelerating success with digital agility.",
  "Bridging dreams and technology.",
  "Innovate, Integrate, Accelerate.",
  "Building digital bridges to success.",
  "Transforming ideas into digital masterpieces.",
  "Elevating businesses with tech solutions.",
  "Coding for a connected world.",
  "Turning visions into digital victories.",
  "Empowering innovation, empowering you.",
  "Design. Develop. Deliver. Dominate",
  "Pioneering digital horizons, one innovation at a time.",
  "Unleashing the power of digital dynamics.",
  "Crafting digital destinies with every click.",
  "Navigating the future with tech-driven solutions.",
  "Creating digital excellence, one byte at a time.",
  "Transformative tech, transformative results.",
  "Innovating today for a digital tomorrow.",
  "Coding dreams into digital frontiers.",
  "Driving digital revolutions, one solution at a time.",
  "Your gateway to digital supremacy.",
  "Crafting the code of the future.",
  "Bringing digital dreams to life.",
  "Where innovation meets digital precision.",
  "Coding the future, connecting the world.",
  "Blazing trails in the digital realm.",
  "Turning tech visions into reality.",
  "The digital craftsmen of tomorrow.",
  "Innovate, Inspire, Implement, Impact.",
  "Coding not just software, but futures.",
  "Technology with a human touch.",
  "Engineering the digital landscape of tomorrow.",
  "The architects of digital innovation.",
  "Bridging the digital divide with innovation.",
  "Tech-driven, future-focused.",
  "Your partners in digital transformation.",
  "Innovation that empowers digital journeys.",
  "We code, we create, we conquer.",
  "Transforming the ordinary into the extraordinary with tech.",
  "Leading the digital charge.",
  "Crafting a smarter, more connected world.",
  "デジタル変革を提供します。",
  "お客様が加速できるよう支援します。",
  "一ピクセルずつ未来を革新します。",
  "デジタル卓越への道をコーディングします。",
  "課題をデジタルソリューションに変換します。",
  "テクノロジーを通じて成功を力づけます。",
  "コードが創造性に出会う場所。",
  "一行のコードで進歩を促進します。",
  "一緒にデジタル世界を形作ります。",
  "夢をデジタルリアリティにエンジニアリングします。",
  "成長のためのテクノロジー。",
  "コードの速さで革新します。",
  "デジタル卓越、我々の核心ミッション。",
  "明日のために今日コーディングします。",
  "デジタル革新で障壁を破ります。",
  "テクノロジーで未来を創造します。",
  "目的とテクノロジーが出会う場所。",
  "デジタル専門知識で産業を革命します。",
  "仮想ソリューションでビジョンを力づけます。",
  "より賢い世界をコーディングします。",
  "デジタルアジリティで成功を加速します。",
  "夢とテクノロジーをつなぐ。",
  "革新、統合、加速。",
  "成功へのデジタル橋を築きます。",
  "アイデアをデジタル傑作に変換します。",
  "テックソリューションでビジネスを高めます。",
  "つながる世界のためにコーディングします。",
  "ビジョンをデジタル勝利に変えます。",
  "革新を力づけ、あなたを力づけます。",
  "デザイン。開発。提供。支配。",
  "一つの革新でデジタルの地平を切り開きます。",
  "デジタルダイナミクスの力を解き放ちます。",
  "一クリックでデジタル運命を創造します。",
  "テック駆動ソリューションで未来を航行します。",
  "一バイトずつデジタル卓越を創造します。",
  "変革的テック、変革的結果。",
  "今日革新してデジタルの明日を。",
  "夢をデジタルフロンティアにコーディングします。",
  "一つのソリューションでデジタル革命を推進します。",
  "デジタル至上へのあなたのゲートウェイ。",
  "未来のコードを創造します。",
  "デジタルの夢を現実にします。",
  "革新がデジタル精度に出会う場所。",
  "未来をコーディングし、世界をつなぎます。",
  "デジタル領域で道を切り開きます。",
  "テックビジョンを現実に変えます。",
  "明日のデジタル職人。",
  "革新、インスパイア、実施、影響。",
];
