# # This workflow will do a clean installation of node dependencies, cache/restore them,
# # build the source code and run tests across different versions of node using Yarn.
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - uses: pnpm/action-setup@v2
#         name: Install pnpm
#         with:
#           version: 8
#           run_install: false
#       - uses: actions/cache@v3
#         name: Setup pnpm chache
#         with:
#           path: ${{ env.STORE_PATH }}
#           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml' )}}
#           restore-kes: ${{ runner.os }}-pnpm-store-
#       - uses: actions/checkout@v3
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "pnpm"
#       - name: Install Dependencies
#         run: pnpm install
#       - name: Run Tests
#         run: yarn test:cov
#       - name: Upload Coverage Report
#         uses: actions/upload-artifact@v2
#         with:
#           name: coverage-report
#           path: coverage/ # adjust this to the path of your coverage report directory

# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node using Yarn.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: yarn test:cov
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/ # adjust this to the path of your coverage report directory

